navsim_log_path: ${oc.env:OPENSCENE_DATA_ROOT}/navsim_logs/${train_test_split.data_split} # path to log annotations
original_sensor_path: ${oc.env:OPENSCENE_DATA_ROOT}/sensor_blobs/${oc.select:train_test_split.original_sensor_split,${train_test_split.data_split}} # path to original sensor blobs
synthetic_sensor_path: ${oc.env:OPENSCENE_DATA_ROOT}/navhard_two_stage/sensor_blobs # path to sensor blobs
synthetic_scenes_path: ${oc.env:OPENSCENE_DATA_ROOT}/navhard_two_stage/synthetic_scene_pickles # path to synthetic scenes
metric_cache_path: ${oc.env:NAVSIM_EXP_ROOT}/metric_cache # path to metric cache
runtime_cache_version: navsim_v2_recogdrive_1
